name: Delete branches created that are not under features

on:
  push:
    #branches: [ main ]
    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: tspascoal/get-user-teams-membership@v1
        id: actorTeams
        with:
          username: ${{ github.actor }}
          organization: SamSmithNZ-dotcom
          #team: '@SamSmithNZ-dotcom/devops-team'
          GITHUB_TOKEN: ${{ secrets.PAT }} 
      - uses: tspascoal/whack-a-branch@v1 
        #if: ${{ !steps.actorTeams.outputs.isTeamMember }}
        id: deletebranches
        with:
          branches-keep: 'main,develop,Release/PI*,SysDemo/PI*,features/*'
          delete-if-no-match: true
          onlyNew: true
          dry-run: false
      - run: echo 'we deleted ${{ steps.deletebranches.outputs.deleted-branches }}'
      - run: echo 'pushed by ${{ github.event.pusher.email }}'
      
