name: Delete branches created that are not under features

on:
  push:
    #branches: [ main ]
    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: tspascoal/whack-a-branch@v1 
        id: deletebranches
        with:
          branches-keep: 'main,releases/*,features/*'
          delete-if-no-match: 'true'
          dry-run: 'false'
      - run: echo we deleted ${{ steps.deletebranches.outputs.deleted-branches }}
      - run: echo pushed by ${{ github.event.pusher.name }}
